# Generated by Django 2.1.3 on 2018-11-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20181115_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.Program'),
        ),
    ]
