# Generated by Django 2.1.3 on 2018-11-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20181115_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='order_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
