# Generated by Django 2.1.3 on 2018-11-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_company_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
