# Generated by Django 2.1.3 on 2018-11-13 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_skill_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ManyToManyField(related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
