# Generated by Django 2.1.3 on 2018-11-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='order_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
